algo = input('Write algo: ')
print('O tipo primivo desse valor é: ', type(algo))
print('This is um digito? ', algo.isdigit())
print('This is um number ? ', algo.isalnum())
print('This is um caracter?', algo.isascii())
print('This is espaço? ',algo.isspace())
print('This is alfabetico? ', algo.isalpha())
print('Thos is alfanumerico? ',algo.isalnum())
print('This is capitalizada? ',algo.istitle())